# Generated by Django 3.2 on 2022-04-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='post', max_length=40),
        ),
    ]
